name: Validate Device Sync

on:
  push:
    branches:
      - device
  pull_request:
    branches:
      - device

env:
  TINYGO_VERSION: v0.39.0

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync device from TinyGo release
        run: |
          echo "Syncing device directory from TinyGo ${{ env.TINYGO_VERSION }}..."
          
          chmod +x scripts/sync-from-release.sh
          ./scripts/sync-from-release.sh "${{ env.TINYGO_VERSION }}" src/device device-temp

      - name: Compare synced content with repository
        run: |
          echo "Comparing synced content with repository device directory..."
          
          if ! diff -r device-temp device; then
            echo "Error: Device directory content does not match TinyGo official release"
            echo "Differences found:"
            diff -r device-temp device || true
            exit 1
          fi
          
          echo "✅ Device directory content matches TinyGo official release"

      - name: Validation summary
        if: success()
        run: |
          echo "========================================="
          echo "✅ All validations passed!"
          echo "========================================="
          echo "✓ Device content matches TinyGo ${{ env.TINYGO_VERSION }}"
          echo "========================================="
