name: Validate Device Sync

on:
  push:
    branches:
      - device
  pull_request:
    branches:
      - device

env:
  TINYGO_VERSION: v0.39.0

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync device content from TinyGo release
        run: |
          chmod +x .github/sync-from-release.sh
          ./.github/sync-from-release.sh ${{ env.TINYGO_VERSION }} src/device device-temp

      - name: Compare synced content with repository
        run: |
          echo "Comparing device-temp/ with device/..."
          
          if ! diff -r device/ device-temp/; then
            echo ""
            echo "Error: device/ directory does not match TinyGo ${{ env.TINYGO_VERSION }} official content"
            echo "Please run: ./.github/sync-from-release.sh ${{ env.TINYGO_VERSION }} src/device device"
            exit 1
          fi
          
          echo "✓ Device content matches TinyGo ${{ env.TINYGO_VERSION }} release"

      - name: Validation Summary
        if: success()
        run: |
          echo "================================"
          echo "✓ All validations passed!"
          echo "================================"
          echo "- Device content sync: verified"
          echo "- TinyGo version: ${{ env.TINYGO_VERSION }}"
          echo "================================"
